Repository Nazar-bnm/ui-internship, pull requests merged in 2019-10, with the labels that each got.

#12 [UIPO-33] mock data
  .eslintrc.js
  JSON-server.md
  README.md
  package-lock.json
  package.json
  src/mockedData/db.json
  src/service/HttpService/httpService.js
Labels: CODE_REVIEW_NEEDED

#19 [UIPO-28] "What is new" component
  jest.config.js
  package-lock.json
  package.json
  src/components/DefaultLayout/index.js
  src/components/Header/Header.js
  src/components/HomePage/index.js
  src/components/MainPage/index.js
  src/components/NotFoundPage/index.js
  src/components/Routes/Routes.js
  src/components/Routes/index.js
  src/components/WhatIsNew/ItemInfo/ItemInfo.js
  src/components/WhatIsNew/ItemInfo/ItemInfo.scss
  src/components/WhatIsNew/ItemInfo/ItemInfo.spec.js
  src/components/WhatIsNew/ItemInfo/index.js
  src/components/WhatIsNew/WhatIsNew.js
  src/components/WhatIsNew/WhatIsNew.scss
  src/components/WhatIsNew/WhatIsNew.spec.js
  src/components/WhatIsNew/index.js
  src/index.html
  src/mockedData/db.json
  src/scss/_styles.scss
Labels: CODE_REVIEW_NEEDED

#24 [UIPO-17] Join us component
  package-lock.json
  package.json
  src/components/ContactDetails/ContactDetails.js
  src/components/ContactDetails/ContactDetails.scss
  src/components/ContactDetails/index.js
  src/components/DefaultLayout/DefaultLayout.js
  src/components/Header/index.js
  src/components/HomePage/HomePage.js
  src/components/JoinUs/JoinUs.js
  src/components/JoinUs/JoinUs.scss
  src/components/JoinUs/JoinUs.spec.js
  src/components/JoinUs/__snapshots__/JoinUs.spec.js.snap
  src/components/JoinUs/index.js
  src/components/ProductListPage/index.js
  src/components/WhatIsNew/ItemInfo/__snapshots__/ItemInfo.spec.js.snap
  src/components/WhatIsNew/__snapshots__/WhatIsNew.spec.js.snap
  src/index.html
  src/scss/_global_styles.scss
  src/scss/_styles.scss
  webpack.config.js
Labels: FINAL_REVIEW_NEEDED

#20 [UIPO-6] Header component
  package-lock.json
  src/components/BurgerMenu/BurgerMenu.js
  src/components/BurgerMenu/BurgerMenu.scss
  src/components/BurgerMenu/__snapshots__/burgerMenu.spec.js.snap
  src/components/BurgerMenu/burgerMenu.spec.js
  src/components/BurgerMenu/index.js
  src/components/Button/Button.js
  src/components/Button/__snapshots__/button.spec.js.snap
  src/components/Button/button.spec.js
  src/components/Button/index.js
  src/components/Dropdown/Dropdown.js
  src/components/Dropdown/Dropdown.scss
  src/components/Dropdown/Dropdown.spec.js
  src/components/Dropdown/__snapshots__/Dropdown.spec.js.snap
  src/components/Dropdown/index.js
  src/components/Header/Header.js
  src/components/Header/Header.scss
  src/components/Header/PageNavigation/PageNavigation.js
  src/components/Header/PageNavigation/PageNavigation.spec.js
  src/components/Header/PageNavigation/__snapshots__/PageNavigation.spec.js.snap
  src/components/Header/PageNavigation/index.js
  src/components/Header/PageSettings/AccountNavigation/AccountNavigation.js
  src/components/Header/PageSettings/AccountNavigation/index.js
  src/components/Header/PageSettings/ContentOptions/ContentOptions.js
  src/components/Header/PageSettings/ContentOptions/index.js
  src/components/Header/PageSettings/PageSettings.js
  src/components/Header/PageSettings/PageSettings.spec.js
  src/components/Header/PageSettings/__snapshots__/PageSettings.spec.js.snap
  src/components/Header/PageSettings/index.js
  src/components/Header/__snapshots__/header.spec.js.snap
  src/components/Header/header.spec.js
  src/components/Input/Input.js
  src/components/Input/__snapshots__/input.spec.js.snap
  src/components/Input/index.js
  src/components/Input/input.spec.js
  src/config/headerMockups.js
  src/fonts/Nunito/Nunito-Bold.ttf
  src/fonts/Nunito/Nunito-Light.ttf
  src/fonts/Nunito/Nunito-Regular.ttf
  src/fonts/Nunito/OFL.txt
  src/fonts/Playfair_Display/OFL.txt
  src/fonts/Playfair_Display/PlayfairDisplay-Black.ttf
  src/fonts/Playfair_Display/PlayfairDisplay-BlackItalic.ttf
  src/fonts/Playfair_Display/PlayfairDisplay-Bold.ttf
  src/fonts/Playfair_Display/PlayfairDisplay-BoldItalic.ttf
  src/fonts/Playfair_Display/PlayfairDisplay-Italic.ttf
  src/fonts/Playfair_Display/PlayfairDisplay-Regular.ttf
  src/fonts/fonts_sample.png
  src/img/background/slider-after.png
  src/img/background/slider.png
  src/img/content/new1.png
  src/img/content/new2.png
  src/img/content/new3.png
  src/scss/_blocks.scss
  src/scss/_fonts.scss
  src/scss/_global_styles.scss
  src/scss/main.scss
Labels: FINAL_REVIEW_NEEDED

#25 [UIPO-32] Blog Article Preview component
  src/components/BlogArticlePreview/BlogArticlePreview.js
  src/components/BlogArticlePreview/BlogArticlePreview.scss
  src/components/BlogArticlePreview/BlogArticlePreview.spec.js
  src/components/BlogArticlePreview/__snapshots__/BlogArticlePreview.spec.js.snap
  src/components/BlogArticlePreview/index.js
  src/components/Footer/ContactDetails/__snapshots__/ContactDetails.spec.js.snap
  src/components/Footer/Footer.spec.js
  src/components/Footer/Linklist/LinkList.spec.js
  src/components/HomePage/HomePage.js
  src/config/footer/index.js
Labels: CODE_REVIEW_NEEDED

#31 [BUG FIX]- Styles fix
  src/components/Footer/ContactDetails/ContactDetails.scss
  src/components/Footer/Footer.js
  src/components/Footer/Footer.scss
  src/components/Footer/Linklist/LinkList.scss
  src/components/Header/Header.js
  src/components/JoinUs/JoinUs.scss
  src/config/footer/index.js
  src/fonts/Nunito/Nunito-Bold.ttf
  src/fonts/Nunito/Nunito-Light.ttf
  src/fonts/Nunito/Nunito-Regular.ttf
  src/fonts/Nunito/OFL.txt
  src/fonts/Playfair_Display/OFL.txt
  src/fonts/Playfair_Display/PlayfairDisplay-Black.ttf
  src/fonts/Playfair_Display/PlayfairDisplay-BlackItalic.ttf
  src/fonts/Playfair_Display/PlayfairDisplay-Bold.ttf
  src/fonts/Playfair_Display/PlayfairDisplay-BoldItalic.ttf
  src/fonts/Playfair_Display/PlayfairDisplay-Italic.ttf
  src/fonts/Playfair_Display/PlayfairDisplay-Regular.ttf
  src/fonts/fonts_sample.png
  src/img/background/slider-after.png
  src/img/background/slider.png
  src/img/content/new1.png
  src/img/content/new2.png
  src/img/content/new3.png
  src/scss/_fonts.scss
  src/scss/_global_styles.scss
  src/scss/_media.scss
  src/scss/main.scss
Labels: CODE_REVIEW_NEEDED

#28 [UIPO-37]- Create unified config
  .env
  config.js
  package-lock.json
  package.json
  src/components/Footer/ContactDetails/ContactDetails.js
  src/components/Footer/Footer.js
  src/components/Header/PageSettings/ContentOptions/ContentOptions.js
  src/config/footer/index.js
  webpack.config.js
Labels: FINAL_REVIEW_NEEDED

#21 [UIPO-25] Product image preview
  jest.config.js
  package.json
  src/assets/img/content/new4.png
  src/components/BurgerMenu/BurgerMenu.scss
  src/components/DefaultLayout/DefaultLayout.js
  src/components/Header/Header.scss
  src/components/Header/PageNavigation/__snapshots__/PageNavigation.spec.js.snap
  src/components/Header/__snapshots__/header.spec.js.snap
  src/components/ProductImage/ProductImage.js
  src/components/ProductImage/ProductImage.scss
  src/components/ProductImage/ProductImage.spec.js
  src/components/ProductImage/__snapshots__/ProductImage.spec.js.snap
  src/components/ProductImage/index.js
  src/config/Footer/index.js
  src/constants/index.js
  src/scss/_global_styles.scss
Labels: FINAL_REVIEW_NEEDED

#33 [UIPO-40] Product order component
  src/components/ProductOrder/ProductOrder.js
  src/components/ProductOrder/ProductOrder.scss
  src/components/ProductOrder/ProductOrder.spec.js
  src/components/ProductOrder/__snapshots__/ProductOrder.spec.js.snap
  src/components/ProductOrder/index.js
  src/config/ProductOrderMockups.js
Labels: FINAL_REVIEW_NEEDED

#32 [UIPO-15] Product items carousel component
  src/assets/img/content/products/shirts/armani-black-1.1.jpg
  src/assets/img/content/products/shirts/armani-black-1.2.jpg
  src/assets/img/content/products/shirts/armani-black-1.3.jpg
  src/assets/img/content/products/shirts/armani-black-1.4.jpg
  src/assets/img/content/products/shirts/armani-jeansblue-1.1.jpg
  src/assets/img/content/products/shirts/armani-jeansblue-1.2.jpg
  src/assets/img/content/products/shirts/armani-jeansblue-1.3.jpg
  src/assets/img/content/products/shirts/armani-jeansblue-1.4.jpg
  src/assets/img/content/products/shirts/levis-red-1.1.jpg
  src/assets/img/content/products/shirts/levis-red-1.2.jpg
  src/assets/img/content/products/shirts/levis-red-1.3.jpg
  src/assets/img/content/products/shirts/levis-red-1.4.jpg
  src/assets/img/content/products/shirts/levis-sol-green-1.1.jpg
  src/assets/img/content/products/shirts/levis-sol-green-1.2.jpg
  src/assets/img/content/products/shirts/levis-sol-green-1.3.jpg
  src/assets/img/content/products/shirts/levis-sol-green-1.4.jpg
  src/assets/img/content/products/shirts/medicine-red-1.1.jpg
  src/assets/img/content/products/shirts/medicine-red-1.2.jpg
  src/assets/img/content/products/shirts/medicine-red-1.3.jpg
  src/assets/img/content/products/shirts/medicine-red-1.4.jpg
  src/assets/img/content/products/shirts/polo-rl-white-1.1.jpg
  src/assets/img/content/products/shirts/polo-rl-white-1.2.jpg
  src/assets/img/content/products/shirts/polo-rl-white-1.3.jpg
  src/assets/img/content/products/shirts/polo-rl-white-1.4.jpg
  src/assets/img/content/products/shirts/polorl-lightblue-1.1.jpg
  src/assets/img/content/products/shirts/polorl-lightblue-1.2.jpg
  src/assets/img/content/products/shirts/polorl-lightblue-1.3.jpg
  src/assets/img/content/products/shirts/polorl-lightblue-1.4.jpg
  src/assets/img/content/products/shirts/scotch-soda-black-1.1.jpg
  src/assets/img/content/products/shirts/scotch-soda-black-1.2.jpg
  src/assets/img/content/products/shirts/scotch-soda-black-1.3.jpg
  src/assets/img/content/products/shirts/scotch-soda-black-1.4.jpg
  src/assets/img/content/products/shirts/tommy-blue-1.1.jpg
  src/assets/img/content/products/shirts/tommy-blue-1.2.jpg
  src/assets/img/content/products/shirts/tommy-blue-1.3.jpg
  src/assets/img/content/products/shirts/tommy-blue-1.4.jpg
  src/assets/img/content/products/shirts/tommy-darkblue-1.1.jpg
  src/assets/img/content/products/shirts/tommy-darkblue-1.2.jpg
  src/assets/img/content/products/shirts/tommy-darkblue-1.3.jpg
  src/assets/img/content/products/shirts/tommy-darkblue-1.4.jpg
  src/components/Carousel/Carousel.js
  src/components/Carousel/Carousel.scss
  src/components/Carousel/Slide/Slide.js
  src/components/Carousel/Slide/Slide.scss
  src/components/Carousel/Slide/index.js
  src/components/Carousel/index.js
  src/components/Carousel/products.json
  src/components/HomePage/HomePage.js
  src/components/ProductList/ProductList.js
  src/components/ProductList/index.js
  src/helpers/carouselHelpers.js
  src/helpers/index.js
Labels: FINAL_REVIEW_NEEDED

#34 [UIPO-38] brands and shipping info
  config.js
  package-lock.json
  package.json
  src/components/Brands/Brands.js
  src/components/Brands/Brands.scss
  src/components/Brands/Brands.spec.js
  src/components/Brands/__snapshots__/Brands.spec.js.snap
  src/components/Brands/index.js
  src/components/DefaultLayout/DefaultLayout.js
  src/components/Routes/Routes.js
  src/components/ShippingInfo/ShippingInfo.js
  src/components/ShippingInfo/ShippingInfo.scss
  src/components/ShippingInfo/ShippingInfo.spec.js
  src/components/ShippingInfo/__snapshots__/ShippingInfo.spec.js.snap
  src/components/ShippingInfo/index.js
  src/mockedDataAPI/db.json
  src/mockedDataForTests/index.js
  src/mockedDataForTests/mockedDataForTests.js
Labels: FINAL_REVIEW_NEEDED

#23 [UIPO-30] - Most popular component
  package-lock.json
  package.json
  src/assets/img/models-most-popular/model1.jpg
  src/assets/img/models-most-popular/model2.jpg
  src/assets/img/models-most-popular/model3.jpg
  src/components/MostPopular/MostPopular.js
  src/components/MostPopular/MostPopular.scss
  src/components/MostPopular/ProductItem/ProductItem.js
  src/components/MostPopular/ProductItem/ProductItem.scss
  src/components/MostPopular/ProductItem/index.js
  src/components/MostPopular/index.js
  src/components/Routes/Routes.js
  src/mockedDataAPI/db.json
  src/scss/_gridsystem.scss
Labels: FINAL_REVIEW_NEEDED

#38 [UIPO-55] - [Enhancement] - Eslint configuration
  .eslintignore
  .eslintrc
  .eslintrc.js
  package-lock.json
  package.json
Labels: CODE_REVIEW_NEEDED

#35 [UIPO-9] Create slideshow
  src/assets/img/background/girl-in-overalls.jpg
  src/assets/img/background/girl-on-boat.jpg
  src/assets/img/background/girls.jpg
  src/assets/img/background/men-in-coat.jpg
  src/components/HomePage/HomePage.js
  src/components/HomePage/Slide/Slide.js
  src/components/HomePage/Slide/Slide.scss
  src/components/HomePage/Slide/Slide.spec.js
  src/components/HomePage/Slide/__snapshots__/Slide.spec.js.snap
  src/components/HomePage/Slide/index.js
  src/components/HomePage/Slideshow/ArrowButton/ArrowButton.js
  src/components/HomePage/Slideshow/ArrowButton/ArrowButton.scss
  src/components/HomePage/Slideshow/ArrowButton/ArrowButton.spec.js
  src/components/HomePage/Slideshow/ArrowButton/__snapshots__/ArrowButton.spec.js.snap
  src/components/HomePage/Slideshow/ArrowButton/index.js
  src/components/HomePage/Slideshow/SlideContainer/SlideContainer.js
  src/components/HomePage/Slideshow/SlideContainer/SlideContainer.scss
  src/components/HomePage/Slideshow/SlideContainer/SlideContainer.spec.js
  src/components/HomePage/Slideshow/SlideContainer/__snapshots__/SlideContainer.spec.js.snap
  src/components/HomePage/Slideshow/SlideContainer/index.js
  src/components/HomePage/Slideshow/Slideshow.js
  src/components/HomePage/Slideshow/Slideshow.scss
  src/components/HomePage/Slideshow/Slideshow.spec.js
  src/components/HomePage/Slideshow/SlideshowDate.js
  src/components/HomePage/Slideshow/__snapshots__/Slideshow.spec.js.snap
  src/components/HomePage/Slideshow/index.js
  src/constants/SlideshowConst/index.js
  src/scss/_styles.scss
Labels: FINAL_REVIEW_NEEDED

#37 [UIPO-41] Create accordion
  src/components/Accordion/Accordion.js
  src/components/Accordion/Accordion.spec.js
  src/components/Accordion/AccordionItem/AccordionItem.js
  src/components/Accordion/AccordionItem/AccordionItem.scss
  src/components/Accordion/AccordionItem/AccordionItem.spec.js
  src/components/Accordion/AccordionItem/__snapshots__/AccordionItem.spec.js.snap
  src/components/Accordion/AccordionItem/index.js
  src/components/Accordion/__snapshots__/Accordion.spec.js.snap
  src/components/Accordion/index.js
  src/components/AccordionPDP/AccordionPDP.js
  src/components/AccordionPDP/AccordionPDP.scss
  src/components/AccordionPDP/AccordionPDP.spec.js
  src/components/AccordionPDP/__snapshots__/AccordionPDP.spec.js.snap
  src/components/AccordionPDP/dataItems.js
  src/components/AccordionPDP/index.js
  src/components/Carousel/Slide/index.js
  src/components/Footer/ContactDetails/ContactDetails.js
  src/components/Footer/ContactDetails/__snapshots__/ContactDetails.spec.js.snap
  src/components/Footer/Footer.js
  src/config/footer/index.js
Labels: FINAL_REVIEW_NEEDED

#40 Product order and image integration
  .eslintrc
  src/components/Button/Button.js
  src/components/Button/Button.scss
  src/components/DefaultLayout/DefaultLayout.js
  src/components/Dropdown/Dropdown.scss
  src/components/Footer/Footer.scss
  src/components/Header/Header.scss
  src/components/HomePage/Slideshow/Slideshow.scss
  src/components/ProductDetailsPage/ProductDetailsPage.js
  src/components/ProductDetailsPage/ProductDetailsPage.scss
  src/components/ProductDetailsPage/ProductDetailsPage.spec.js
  src/components/ProductDetailsPage/ProductDetailsPageWrapper.js
  src/components/ProductDetailsPage/__snapshots__/ProductDetailsPage.spec.js.snap
  src/components/ProductDetailsPage/index.js
  src/components/ProductImage/ProductImage.js
  src/components/ProductImage/ProductImage.scss
  src/components/ProductImage/ProductImage.spec.js
  src/components/ProductImage/__snapshots__/ProductImage.spec.js.snap
  src/components/ProductOrder/ProductOrder.js
  src/components/ProductOrder/ProductOrder.scss
  src/components/ProductOrder/ProductOrder.spec.js
  src/components/ProductOrder/__snapshots__/ProductOrder.spec.js.snap
  src/components/Routes/Routes.js
  src/constants/index.js
  src/scss/_styles.scss
Labels: FINAL_REVIEW_NEEDED

#42 [UIPO-44] Reusable Section Header Component
  src/components/Heading/Heading.js
  src/components/Heading/Heading.scss
  src/components/Heading/Heading.spec.js
  src/components/Heading/__snapshots__/Heading.spec.js.snap
  src/components/Heading/index.js
Labels: FINAL_REVIEW_NEEDED

#47 Create simple routing transition
  package-lock.json
  src/components/DefaultLayout/DefaultLayout.js
  src/components/Routes/Routes.js
  src/components/Routes/Routes.scss
Labels: CODE_REVIEW_NEEDED

#41 [UIPO-43] Product list component
  jest.config.js
  package-lock.json
  package.json
  src/actions/actionsProductList.js
  src/components/Header/Header.js
  src/components/Header/PageSettings/ContentOptions/ContentOptions.js
  src/components/HomePage/Slide/Slide.js
  src/components/ProductDetailsPage/ProductDetailsPageWrapper.js
  src/components/ProductList/ItemsList/ItemListContainer.spec.js
  src/components/ProductList/ItemsList/ItemsList.js
  src/components/ProductList/ItemsList/ItemsList.scss
  src/components/ProductList/ItemsList/ItemsList.spec.js
  src/components/ProductList/ItemsList/ItemsListContainer.js
  src/components/ProductList/ItemsList/__snapshots__/ItemListContainer.spec.js.snap
  src/components/ProductList/ItemsList/__snapshots__/ItemsList.spec.js.snap
  src/components/ProductList/ItemsList/index.js
  src/components/ProductList/ProductList.js
  src/components/ProductList/ProductList.scss
  src/components/ProductList/ProductList.spec.js
  src/components/ProductList/ProductListNavigation/ProductListNavigation.js
  src/components/ProductList/ProductListNavigation/ProductListNavigation.spec.js
  src/components/ProductList/ProductListNavigation/ProductListNavigationContainer.js
  src/components/ProductList/ProductListNavigation/__snapshots__/ProductListNavigation.spec.js.snap
  src/components/ProductList/ProductListNavigation/index.js
  src/components/ProductList/__snapshots__/ProductList.spec.js.snap
  src/components/ProductList/index.js
  src/components/ProductOrder/ProductOrder.js
  src/components/ProductOrder/__snapshots__/ProductOrder.spec.js.snap
  src/components/shared/Button/Button.js
  src/components/shared/Button/Button.scss
  src/components/shared/Button/__snapshots__/button.spec.js.snap
  src/components/shared/Button/button.spec.js
  src/components/shared/Button/index.js
  src/components/shared/Dropdown/Dropdown.js
  src/components/shared/Dropdown/Dropdown.scss
  src/components/shared/Dropdown/Dropdown.spec.js
  src/components/shared/Dropdown/__snapshots__/Dropdown.spec.js.snap
  src/components/shared/Dropdown/index.js
  src/components/shared/index.js
  src/constants/actionTypes/index.js
  src/constants/index.js
  src/mockedDataAPI/db.json
  src/mockedDataForTests/mockedDataForTests.js
  src/reducers/index.js
  src/reducers/reducerProductList.js
Labels: FINAL_REVIEW_NEEDED

#45 [UIPO-50] Carousel refactor and test coverage
  src/components/Carousel/Carousel.js
  src/components/Carousel/Carousel.scss
  src/components/Carousel/Carousel.spec.js
  src/components/Carousel/__snapshots__/Carousel.spec.js.snap
Labels: FINAL_REVIEW_NEEDED

#36 [UIPO - 13 ] Create wishlist page
  package-lock.json
  src/actions/actionsAPIcall.js
  src/actions/actionsCounter.js
  src/actions/actionsWishlist.js
  src/actions/fetchProducts.js
  src/assets/img/content/img-no-cartitems.png
  src/components/Counter/Counter.js
  src/components/Counter/index.js
  src/components/DefaultLayout/DefaultLayout.js
  src/components/DefaultLayout/DefaultLayoutContainer.js
  src/components/DefaultLayout/index.js
  src/components/Header/PageSettings/AccountNavigation/AccountNavigation.js
  src/components/Routes/Routes.js
  src/components/WishlistPage/WishlistItem/WishlistItem.js
  src/components/WishlistPage/WishlistItem/WishlistItem.scss
  src/components/WishlistPage/WishlistItem/index.js
  src/components/WishlistPage/WishlistPage.js
  src/components/WishlistPage/WishlistPage.scss
  src/components/WishlistPage/WishlistPageContainer.js
  src/components/WishlistPage/index.js
  src/constants/actionTypes/index.js
  src/containers/Counter/index.js
  src/mockedDataAPI/db.json
  src/reducers/index.js
  src/reducers/reducerAPIcall.js
  src/reducers/reducerCounter.js
  src/reducers/reducerWishlist.js
Labels: FIXES_NEEDED

#48 [UIPO-42] Feature/filters
  .eslintrc
  config.js
  package-lock.json
  src/actions/actionsFilter.js
  src/assets/img/productListPage/collection_photo.jpg
  src/assets/img/productListPage/kids.jpg
  src/assets/img/productListPage/men.jpg
  src/assets/img/productListPage/women.jpg
  src/components/CollectionPoster/CollectionPoster.js
  src/components/CollectionPoster/CollectionPoster.scss
  src/components/CollectionPoster/index.js
  src/components/DefaultLayout/DefaultLayout.js
  src/components/Header/Header.js
  src/components/Header/__snapshots__/header.spec.js.snap
  src/components/Heading/Heading.js
  src/components/HomePage/HomePage.js
  src/components/ProductListPage/CheckBoxList/CheckBoxList.js
  src/components/ProductListPage/CheckBoxList/CheckBoxListContainer.js
  src/components/ProductListPage/CheckBoxList/index.js
  src/components/ProductListPage/Filters/Filters.js
  src/components/ProductListPage/Filters/Filters.scss
  src/components/ProductListPage/Filters/index.js
  src/components/ProductListPage/ProductListPage.js
  src/components/ProductListPage/ProductListPage.scss
  src/components/ProductListPage/ProductListPageContainer.js
  src/components/ProductListPage/index.js
  src/components/Routes/Routes.js
  src/components/shared/CheckBox/CheckBox.js
  src/components/shared/CheckBox/CheckBox.scss
  src/components/shared/CheckBox/index.js
  src/config/headerMockups.js
  src/constants/actionTypes/index.js
  src/mockedDataAPI/db.json
  src/reducers/index.js
  src/reducers/reducerFilter.js
  src/reducers/reducerProductList.js
  src/scss/_styles.scss
Labels: CODE_REVIEW_NEEDED

#55 Product list, Product order and Header/Content options changed to use the new dropdown
  package-lock.json
  package.json
  src/components/Header/PageSettings/ContentOptions/ContentOptions.js
  src/components/ProductList/ProductList.js
  src/components/ProductList/ProductListNavigation/ProductListNavigation.js
  src/components/ProductList/ProductListNavigation/ProductListNavigationContainer.js
  src/components/ProductList/ProductListNavigation/__snapshots__/ProductListNavigation.spec.js.snap
  src/components/ProductList/__snapshots__/ProductList.spec.js.snap
  src/components/ProductOrder/ProductOrder.js
  src/components/ProductOrder/__snapshots__/ProductOrder.spec.js.snap
  src/components/shared/Dropdown/Dropdown.js
  src/components/shared/Dropdown/Dropdown.spec.js
  src/components/shared/Dropdown/__snapshots__/Dropdown.spec.js.snap
  src/reducers/reducerProductList.js
Labels: FINAL_REVIEW_NEEDED

#43 Create a reusable modal
  src/components/Modal/Modal.js
  src/components/Modal/Modal.scss
  src/components/Modal/Modal.spec.js
  src/components/Modal/__snapshots__/Modal.spec.js.snap
  src/components/Modal/index.js
  src/components/Modal/testModal.js
  src/config/Footer/index.js
Labels: FINAL_REVIEW_NEEDED

#51 UIPO-47 - [Feature/cart page]
  config.js
  src/actions/actionsCart.js
  src/assets/img/background/offer.jpg
  src/assets/img/content/img-no-cartitems.png
  src/components/CartPage/CartItem/CartItem.js
  src/components/CartPage/CartItem/CartItem.scss
  src/components/CartPage/CartItem/index.js
  src/components/CartPage/CartPage.js
  src/components/CartPage/CartPage.scss
  src/components/CartPage/CartPageContainer.js
  src/components/CartPage/index.js
  src/components/DefaultLayout/DefaultLayout.js
  src/components/Header/Header.js
  src/components/Header/HeaderContainer.js
  src/components/Header/index.js
  src/components/Routes/Routes.js
  src/constants/actionTypes/index.js
  src/reducers/index.js
  src/reducers/reducerCart.js
Labels: FIXES_NEEDED
