Repository Nazar-bnm/ui-internship, pull requests merged in 2019-11, with the labels that each got.

#62 [UIPO-49]&[UIPO-73] Add quick view to Product Item
  .env
  package-lock.json
  src/actions/fetchProducts.js
  src/components/Carousel/Carousel.js
  src/components/Carousel/Carousel.scss
  src/components/Carousel/__snapshots__/Carousel.spec.js.snap
  src/components/HomePage/Slideshow/Slideshow.js
  src/components/Modal/Modal.scss
  src/components/MostPopular/MostPopular.js
  src/components/MostPopular/MostPopularContainer.js
  src/components/MostPopular/ProductItem/ProductItem.js
  src/components/MostPopular/ProductItem/ProductItem.scss
  src/components/MostPopular/ProductItem/ProductItemContainer.js
  src/components/MostPopular/ProductItem/index.js
  src/components/ProductDetailsPage/__snapshots__/ProductDetailsPage.spec.js.snap
  src/components/ProductList/ItemsList/ItemsList.spec.js
  src/components/ProductList/ItemsList/__snapshots__/ItemsList.spec.js.snap
  src/components/ProductOrder/ProductOrder.js
  src/components/ProductOrder/__snapshots__/ProductOrder.spec.js.snap
  src/components/WishlistPage/WishlistItem/WishlistItem.js
  src/components/WishlistPage/WishlistPage.js
  src/config/ProductOrderMockups.js
  src/constants/notificationData.js
Labels: CODE_REVIEW_NEEDED

#58 [UIPO-70] Carousel: fix responsive design and console warning
  src/components/Carousel/Carousel.js
  src/components/Carousel/Carousel.scss
  src/components/Carousel/Carousel.spec.js
  src/components/Carousel/__snapshots__/Carousel.spec.js.snap
  src/config/footer/index.js
Labels: FINAL_REVIEW_NEEDED

#61 [UIPO-43] Product list component
  config.js
  src/assets/img/productListPage/man.jpg
  src/assets/img/productListPage/woman.jpg
  src/components/BlogArticlePreview/BlogArticlePreview.js
  src/components/BlogArticlePreview/BlogArticlePreview.scss
  src/components/BlogArticlePreview/BlogArticlePreview.spec.js
  src/components/BlogArticlePreview/__snapshots__/BlogArticlePreview.spec.js.snap
  src/components/Brands/Brands.js
  src/components/Brands/Brands.scss
  src/components/Brands/Brands.spec.js
  src/components/Brands/__snapshots__/Brands.spec.js.snap
  src/components/BurgerMenu/BurgerMenu.scss
  src/components/Carousel/Carousel.scss
  src/components/Carousel/index.js
  src/components/Footer/Linklist/LinkList.js
  src/components/Footer/index.js
  src/components/Header/Header.js
  src/components/Header/Header.scss
  src/components/Header/PageNavigation/PageNavigation.js
  src/components/Header/PageSettings/ContentOptions/ContentOptions.js
  src/components/Header/__snapshots__/header.spec.js.snap
  src/components/HomePage/HomePage.js
  src/components/HomePage/Slide/Slide.js
  src/components/Input/Input.js
  src/components/Input/__snapshots__/input.spec.js.snap
  src/components/MostPopular/MostPopular.scss
  src/components/MostPopular/index.js
  src/components/NotFoundPage/NotFoundPage.js
  src/components/ProductImage/ProductImage.scss
  src/components/ProductList/ItemsList/ItemListContainer.spec.js
  src/components/ProductList/ItemsList/ItemsList.js
  src/components/ProductList/ItemsList/ItemsListContainer.js
  src/components/ProductList/ItemsList/__snapshots__/ItemListContainer.spec.js.snap
  src/components/ProductList/ProductList.js
  src/components/ProductList/ProductList.scss
  src/components/ProductList/ProductListNavigation/ProductListNavigation.js
  src/components/ProductList/ProductListNavigation/__snapshots__/ProductListNavigation.spec.js.snap
  src/components/ProductList/__snapshots__/ProductList.spec.js.snap
  src/components/ProductListPage/ProductListPage.js
  src/components/ProductListPage/ProductListPageContainer.js
  src/components/Routes/Routes.js
  src/components/Shared/Notifications/__snapshots__/Notifications.spec.js.snap
  src/components/WhatIsNew/ItemInfo/ItemInfo.scss
  src/components/WhatIsNew/WhatIsNew.js
  src/components/WhatIsNew/WhatIsNew.scss
  src/components/WhatIsNew/__snapshots__/WhatIsNew.spec.js.snap
  src/components/shared/Button/button.spec.js
  src/components/shared/Dropdown/Dropdown.scss
  src/components/shared/Notifications/Notifications.js
  src/components/shared/Notifications/Notifications.scss
  src/components/shared/Notifications/Notifications.spec.js
  src/components/shared/Notifications/NotificationsContainer.js
  src/components/shared/Notifications/__snapshots__/Notifications.spec.js.snap
  src/components/shared/Notifications/index.js
  src/config/headerMockups.js
  src/constants/brandID.js
  src/constants/index.js
  src/mockedDataAPI/db.json
  src/reducers/reducerProductList.js
Labels: FINAL_REVIEW_NEEDED

#66 [UIPO-54] Make Carousel work vertical
  package-lock.json
  src/components/Accordion/Accordion.js
  src/components/Carousel/Carousel.js
  src/components/Carousel/Carousel.scss
  src/components/Carousel/Carousel.spec.js
  src/components/Carousel/__snapshots__/Carousel.spec.js.snap
  src/components/HomePage/Slide/__snapshots__/Slide.spec.js.snap
  src/components/MostPopular/MostPopular.js
  src/components/MostPopular/ProductItem/ProductItem.js
  src/components/MostPopular/ProductItem/ProductItem.scss
  src/components/MostPopular/ProductItem/ProductItem.spec.js
  src/components/MostPopular/ProductItem/__snapshots__/ProductItem.spec.js.snap
  src/components/ProductDetailsPage/ProductDetailsPage.js
  src/components/ProductDetailsPage/ProductDetailsPage.scss
  src/components/ProductDetailsPage/ProductDetailsPage.spec.js
  src/components/ProductDetailsPage/ProductDetailsPageContainer.js
  src/components/ProductDetailsPage/__snapshots__/ProductDetailsPage.spec.js.snap
  src/components/ProductDetailsPage/index.js
  src/components/ProductImage/ProductImage.js
  src/components/ProductImage/ProductImage.scss
  src/components/ProductImage/__snapshots__/ProductImage.spec.js.snap
  src/components/ProductList/ItemsList/ItemsList.js
  src/components/ProductList/ProductListNavigation/__snapshots__/ProductListNavigation.spec.js.snap
  src/components/ProductOrder/ProductOrder.js
  src/components/ProductOrder/ProductOrder.scss
  src/components/ProductOrder/__snapshots__/ProductOrder.spec.js.snap
  src/components/Routes/Routes.js
  src/components/WishlistPage/WishlistItem/WishlistItem.js
  src/config/dataItemsAccordion.js
  src/helpers/carouselHelpers.js
  src/shared/Button/Button.js
  src/shared/Dropdown/Dropdown.js
  webpack.config.js
Labels: FIXES_NEEDED

#70 [UIPO-51] Feature/preloader
  jest.config.js
  src/assets/img/preloader/circle.svg
  src/components/Preloader/Preloader.js
  src/components/Preloader/Preloader.scss
  src/components/Preloader/Preloader.spec.js
  src/components/Preloader/__snapshots__/Preloader.spec.js.snap
  src/components/Preloader/index.js
  src/scss/_styles.scss
Labels: CODE_REVIEW_NEEDED

#67 Price range slider
  src/actions/actionsFilter.js
  src/components/Accordion/Accordion.js
  src/components/ProductListPage/CheckBoxList/CheckBoxList.js
  src/components/ProductListPage/CheckBoxList/CheckBoxListContainer.js
  src/components/ProductListPage/CheckBoxList/index.js
  src/components/ProductListPage/Filters/Filters.js
  src/components/ProductListPage/Filters/Filters.scss
  src/components/ProductListPage/PriceRangeSlider/PriceRangeSlider.js
  src/components/ProductListPage/PriceRangeSlider/PriceRangeSlider.scss
  src/components/ProductListPage/PriceRangeSlider/index.js
  src/components/ProductListPage/ProductListPage.js
  src/components/ProductListPage/ProductListPage.scss
  src/components/ProductListPage/ProductListPageContainer.js
  src/constants/actionTypes/index.js
  src/reducers/reducerFilter.js
  src/shared/CheckBox/CheckBox.js
Labels: FIXES_NEEDED

#71 Fix/add to cart functionality
  src/actions/actionsCart.js
  src/components/CartPage/CartItem/CartItem.js
  src/components/CartPage/CartPage.js
  src/components/CartPage/CartPageContainer.js
  src/components/ProductDetailsPage/ProductDetailsPage.js
  src/components/ProductDetailsPage/ProductDetailsPageWrapper.js
  src/components/ProductDetailsPage/__snapshots__/ProductDetailsPage.spec.js.snap
  src/components/ProductOrder/ProductOrder.js
  src/components/ProductOrder/ProductOrder.scss
  src/components/ProductOrder/ProductOrder.spec.js
  src/components/ProductOrder/ProductOrderContainer.js
  src/components/ProductOrder/__snapshots__/ProductOrder.spec.js.snap
  src/components/ProductOrder/index.js
  src/constants/actionTypes/index.js
  src/reducers/reducerCart.js
  src/shared/Dropdown/Dropdown.js
  src/shared/Dropdown/Dropdown.scss
  src/shared/DynamicInput/DynamicInput.js
  src/shared/DynamicInput/DynamicInput.scss
  src/shared/DynamicInput/index.js
Labels: CODE_REVIEW_NEEDED

#72 UIPO-56 Blog Section and Blog Item
  .env
  config.js
  src/actions/actionsBlogPage.js
  src/components/BlogPage/BlogItem/BlogItem.js
  src/components/BlogPage/BlogItem/BlogItem.scss
  src/components/BlogPage/BlogItem/BlogItem.spec.js
  src/components/BlogPage/BlogItem/__snapshots__/BlogItem.spec.js.snap
  src/components/BlogPage/BlogItem/index.js
  src/components/BlogPage/BlogPage.js
  src/components/BlogPage/BlogPage.scss
  src/components/BlogPage/BlogPage.spec.js
  src/components/BlogPage/BlogPageContainer.js
  src/components/BlogPage/__snapshots__/BlogPage.spec.js.snap
  src/components/BlogPage/index.js
  src/components/Header/__snapshots__/header.spec.js.snap
  src/components/Routes/Routes.js
  src/constants/actionTypes/index.js
  src/mockedDataAPI/db.json
  src/mockedDataForTests/mockedDataForTests.js
  src/reducers/index.js
  src/reducers/reducerBlogPage.js
  src/scss/_styles.scss
  src/shared/Button/Button.js
  src/shared/Button/Button.scss
Labels: FINAL_REVIEW_NEEDED

#73 [UIPO-76] fixed unexpected scroll to the footer when opening a new subpage
  src/components/ScrollToTop/ScrollToTop.js
  src/components/ScrollToTop/index.js
  src/index.js
Labels: CODE_REVIEW_NEEDED

#74 Product List, Checkout and Blog enhancement
  src/components/BlogPage/BlogItem/BlogItem.scss
  src/components/Checkout/BillingInfo/BillingInfo.js
  src/components/Checkout/BillingInfo/BillingInfoContainer.js
  src/components/Checkout/BillingInfo/__snapshots__/BillingInfo.spec.js.snap
  src/components/Checkout/BillingInfo/index.js
  src/components/Checkout/LoginRegister/LoginRegister.js
  src/components/Checkout/LoginRegister/LoginRegister.scss
  src/components/Checkout/LoginRegister/LoginRegisterContainer.js
  src/components/Checkout/LoginRegister/__snapshots__/LoginRegister.spec.js.snap
  src/components/Checkout/LoginRegister/index.js
  src/components/Checkout/ShippingMethod/ShippingMethod.js
  src/components/Checkout/ShippingMethod/__snapshots__/ShippingMethod.spec.js.snap
  src/components/Checkout/__snapshots__/Checkout.spec.js.snap
  src/components/Header/PageSettings/AccountNavigation/AccountNavigation.js
  src/components/ProductList/ItemsList/ItemsList.js
  src/components/ProductList/ItemsList/ItemsListContainer.js
  src/constants/notificationData.js
Labels: FINAL_REVIEW_NEEDED

#76 [UIPO-66] Google maps integration
  .jest/enzyme.setup.js
  src/components/Footer/Footer.js
  src/components/GoogleMap/GoogleMap.js
  src/components/GoogleMap/GoogleMap.scss
  src/components/GoogleMap/GoogleMap.spec.js
  src/components/GoogleMap/__snapshots__/GoogleMap.spec.js.snap
  src/components/GoogleMap/index.js
  src/config/googleMapAPIkey.js
Labels: FINAL_REVIEW_NEEDED

#78 [UIPO-57] Feature/labels
  .babelrc
  jest.config.js
  package-lock.json
  package.json
  src/actions/actionsBlogPage.js
  src/components/BlogPage/BlogPage.js
  src/components/BlogPage/BlogPage.scss
  src/components/BlogPage/BlogPage.spec.js
  src/components/BlogPage/BlogPageContainer.js
  src/components/BlogPage/__snapshots__/BlogPage.spec.js.snap
  src/components/Labels/Labels.js
  src/components/Labels/Labels.scss
  src/components/Labels/Labels.spec.js
  src/components/Labels/__snapshots__/Labels.spec.js.snap
  src/components/Labels/index.js
  src/components/ProductListPage/Filters/Filters.scss
  src/components/ProductListPage/ProductListPage.scss
  src/constants/actionTypes/index.js
  src/mockedDataAPI/db.json
  src/reducers/reducerBlogPage.js
  src/reducers/reducerFilter.js
  src/scss/_styles.scss
Labels: FINAL_REVIEW_NEEDED

#79 [UIPO-60] Create pagination
  src/components/Pagination/Pagination.js
  src/components/Pagination/Pagination.scss
  src/components/Pagination/Pagination.spec.js
  src/components/Pagination/__snapshots__/Pagination.spec.js.snap
  src/components/Pagination/index.js
  src/components/ProductList/ItemsList/ItemsList.js
  src/components/ProductList/ItemsList/ItemsList.scss
  src/components/ProductList/ItemsList/ItemsListContainer.js
  src/components/ProductList/ProductList.js
  src/components/ProductList/ProductList.scss
  src/components/ProductList/ProductListContainer.js
  src/components/ProductList/__snapshots__/ProductList.spec.js.snap
  src/components/ProductList/index.js
  src/reducers/reducerFilter.js
Labels: FIXES_NEEDED

#83 [UIPO-80] Blog section on Home page receives data from the server
  src/components/BlogArticlePreview/BlogArticlePreview.js
  src/components/BlogArticlePreview/BlogArticlePreview.scss
  src/components/BlogArticlePreview/__snapshots__/BlogArticlePreview.spec.js.snap
  src/components/HomePage/HomePage.js
  src/components/HomePage/HomePage.scss
Labels: CODE_REVIEW_NEEDED

#84 Fix after demo
  src/components/MostPopular/ProductItem/ProductItem.js
  src/components/MostPopular/ProductItem/ProductItem.spec.js
  src/components/Pagination/Pagination.js
  src/components/ProductOrder/ProductOrder.js
  src/components/ProductOrder/ProductOrderContainer.js
  src/reducers/reducerCart.js
  src/shared/DynamicInput/DynamicInput.js
  src/shared/Notifications/Notifications.scss
Labels: FINAL_REVIEW_NEEDED

#86 [UIPO-68] You will also love
  src/components/CartPage/CartPage.js
  src/components/ProductOrder/ProductOrder.js
  src/components/YouWillAlsoLove/YouWillAlsoLove.js
  src/components/YouWillAlsoLove/YouWillAlsoLove.scss
  src/components/YouWillAlsoLove/YouWillAlsoLove.spec.js
  src/components/YouWillAlsoLove/YouWillAlsoLoveContainer.js
  src/components/YouWillAlsoLove/__snapshots__/YouWillAlsoLove.spec.js.snap
  src/components/YouWillAlsoLove/index.js
Labels: CODE_REVIEW_NEEDED

#87 [UIPO-86] Login page (part I)
  package-lock.json
  package.json
  src/components/BlogArticlePreview/BlogArticlePreview.js
  src/components/Header/PageSettings/AccountNavigation/AccountNavigation.js
  src/components/LoginPage/LoginPage.js
  src/components/LoginPage/LoginPage.scss
  src/components/LoginPage/LoginPage.spec.js
  src/components/LoginPage/LoginPageContainer.js
  src/components/LoginPage/__snapshots__/LoginPage.spec.js.snap
  src/components/LoginPage/index.js
  src/components/MostPopular/ProductItem/ProductItem.js
  src/components/ProductList/ProductList.scss
  src/components/ProductOrder/ProductOrder.js
  src/components/ProductOrder/ProductOrder.scss
  src/components/Routes/Routes.js
  src/shared/DynamicInput/DynamicInput.scss
Labels: CODE_REVIEW_NEEDED

#88 [UIPO-94] Update Lodash
  package-lock.json
  package.json
  src/components/Carousel/Carousel.js
  src/components/ProductList/ItemsList/ItemsList.js
  src/reducers/reducerFilter.js
Labels: CODE_REVIEW_NEEDED

#92 [UIPO-82] Replace mocked brands data to data that comes from server
  .env
  src/components/Brands/Brands.js
  src/components/Brands/Brands.scss
  src/components/Header/Header.js
  src/components/Header/__snapshots__/header.spec.js.snap
  src/components/WebsiteNavigation/WebsiteNavigation.scss
Labels: CODE_REVIEW_NEEDED

#90 [UIPO-89] Implement country search on registration
  package-lock.json
  package.json
  src/components/Checkout/BillingInfo/BillingInfo.js
  src/components/Checkout/BillingInfo/BillingInfo.scss
  src/components/Checkout/BillingInfo/BillingInfo.spec.js
  src/components/Checkout/BillingInfo/__snapshots__/BillingInfo.spec.js.snap
Labels: FINAL_REVIEW_NEEDED

#85 [UIPO-79] What's new: add hover on images
  src/components/WhatIsNew/ItemInfo/ItemInfo.js
  src/components/WhatIsNew/WhatIsNew.js
  src/components/WhatIsNew/WhatIsNew.scss
  src/components/WhatIsNew/__snapshots__/WhatIsNew.spec.js.snap
Labels: review by teammates

#75 UIPO-69 Payment system integration with Stripe
  package-lock.json
  package.json
  src/actions/actionsCart.js
  src/components/CartPage/CartPage.js
  src/components/CartPage/CartPage.scss
  src/components/CartPage/CartPage.spec.js
  src/components/CartPage/CartPageContainer.js
  src/components/CartPage/__snapshots__/CartPage.spec.js.snap
  src/components/Checkout/Payment/Payment.js
  src/components/Checkout/Payment/Payment.spec.js
  src/components/Checkout/Payment/PaymentContainer.js
  src/components/Checkout/Payment/__snapshots__/Payment.spec.js.snap
  src/components/Checkout/Payment/index.js
  src/components/Checkout/__snapshots__/Checkout.spec.js.snap
  src/config/stripeKey.js
  src/constants/actionTypes/index.js
  src/constants/notificationData.js
  src/reducers/reducerCart.js
Labels: FINAL_REVIEW_NEEDED
